import type { Metadata } from "next";
import React from "react";
// This simple relative path is the *required* standard for global CSS in the root layout.
import "./globals.css"; 
// import { ThemeProvider } from "@/components/theme-provider"


export const metadata: Metadata = {
  title: "NovaLearn", // Project Name Update
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body>
        <main>
        {children}
      </main>
      </body>
    </html>
  );
}